version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlops_user
      POSTGRES_PASSWORD: mlops_password
      POSTGRES_DB: mlops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlops-app:
    build:
      context: .
      dockerfile: dockerfile_model
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mlops_db
      - DB_USER=mlops_user
      - DB_PASSWORD=mlops_password
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./output:/app/output

volumes:
  postgres_data: 